### ISSUE TITLE
TODO before v0.3

### ISSUE THREAD

**Issue by mpizenberg** [pubgrub-rs/guide#7]
TODO:

- [ ] [v0.2 -> v0.3 upgrade section](https://github.com/pubgrub-rs/guide/pull/6)
- [ ] section + reference impl for pre-releases
- [ ] add specific info about property testing `VersionSet` for people re-implementing it
- [ ] general upgrade of the guide to fit v0.3 narrative

**Comment by konstin** [comment]
The guide has been updated and the release went out.
